- oclint-driver/lib/Driver.cpp
In r241310, the Job class was removed. For a job list, use the JobList class.
> Catch up with clang driver changes

- oclint-rules/rules/convention/BaseClassDestructorShouldBeVirtualOrProtectedRule.cpp
- oclint-rules/rules/convention/DestructorOfVirtualClassRule.cpp
While Testing the code from a friend i ran into a segfault which can be tracked down with the following example code. This patch should fix the missbehaviour accordingly
Testcode
#include <iostream>
namespace a {
class aa;
}
int main(void) {
std::cout << 1n;
return 0;
}
> Allow the usage of the forward declarations within the code

- oclint-rules/rules/unused/UnusedLocalVariableRule.cpp
This changes allow to suppress the complains about unused variables.
When using RAII such as std::lock_guard the intention of do not access the variable further is intended
There are two variables, which allow to change the baviour:
RAII_DEFAULT_CLASSES which suppress std::lock_guard and std::unique_lock
RAII_CUSTOM_CLASSES to allow the user to define further own created parts
At the moment there are no tests appended and maybe further classes should be appended to the default definition
> Appended the suppression of unused local variables using RAII

- oclint-rules/rules/unused/UnusedLocalVariableRule.cpp
- oclint-rules/test/unused/UnusedLocalVariableRuleTest.cpp
Sorry for the long delay and not appending tests on the first pull requests.
I've now appended a few of them. At the moment it seems like they are not working, after a complete rebase. Seems like it is related to the appending of those two lines:
+        CXXConstructExpr* expr = dyn_cast_or_null<CXXConstructExpr>(varDecl->getInit());
+        return expr && expr->getNumArgs() == 1;
As i am not sure what the intention of them is, they might need a check. At least the things look fine up to those lines. If I have not done something wrong, the test should pass without any complains (at least they do without them)
> Appended a few tests for RAII support

- oclint-rules/lib/helper/SuppressHelper.cpp
- oclint-rules/test/helper/SuppressHelperTest.cpp
[Official documentation](http://oclint-docs.readthedocs.org/en/stable/howto/suppress.html) has example of both `//!OCLINT` and `//!OCLint` warnings suppress comments.
However, actual implementation supports only `//!OCLINT`.
A bit confusing, takes a while to figure out that documentation is wrong.
This change will use case-insensitive check for "oclint" match.
Additionally, it allows to have space after `//!`, e.g. `//! OCLINT`, which is a valid form of raw comment.
P.S.
Stuff like `//!         oclint` will also work, but it's rather undocumented feature :).
> Allow spaces and varied case in suppress comments

- .travis.yml
- oclint-rules/test/CMakeLists.txt
- oclint-rules/test/headers/TestRuleOnCode.cpp
- oclint-rules/test/headers/TestRuleOnCode.h
- oclint-scripts/travis
This PR aims to improve build times and the usefulness of the build.
* ~~Split the build into multiple modules~~
* ~~Split header files into source and header~~
* Only include what is actually needed for each test file
* Merge oclint-rules test files into one or a few executables
* Do not rerun tests of the dependencies of every module
Caching for osx and trusty builds is only enabled for private repositories.
Is seems like the osx machines only have one core, despite travis claiming otherwise. Not much we can do about that.
> [WIP] Improve travis build

- oclint-scripts/oclintscripts/path.py
- oclint-scripts/test
- oclint-scripts/travis
This enables us to simply build the dependencies without tests and then
just run the tests for the module we want to test.
I am not sure if this actually reduces the total time spend in the CI tests, but at least this way we dont run the tests for the dependencies multiple times.
I am not sure why the tests are build in a different directory. Is there some script that requires this?
> Use the same dir for tests and normal builds

- .travis.yml
There seems to be no way to separate the linux and osx builds on coveralls.
> Collect coverage inormation for osx

- oclint-driver/lib/Driver.cpp
The DiagnosticConsumer gets allocated with new but is never deleted. The
engine is explicitly told to not take ownership of the consumer. This
would make sense if the consumer is later freed by oclint, but this
never happens. Instead we should just let the engine take ownership of
the client so that it gets deleted alongside the enngine.
This might be related to #275
> Fix DiagnosticConsumer memory leak

- .travis.yml
- oclint-core/cmake/OCLintConfig.cmake
- oclint-driver/lib/Driver.cpp
- oclint-rules/lib/helper/SuppressHelper.cpp
- oclint-rules/rules/design/AvoidDefaultArgumentsOnVirtualMethodsRule.cpp
- oclint-rules/rules/design/AvoidPrivateStaticMembersRule.cpp
- oclint-scripts/oclintscripts/path.py
- oclint-scripts/oclintscripts/version.py
I don't know if it was planned, but I needed it, so I did it ^^
The prebuilt LLVM packages url and the LLVM svn tag have been updated. I also updated the Ubuntu package url to 16.04 LTS (was 14.04).
A quick test on a project full of errors did not raise any obvious bug, but it will need more testing before being merged.
Let me know if I forgot anything.
EDIT: Your CI Glibc seems too old to pass the build, that's odd... Is Debian not up to date enough or do you need to update?
> Update to LLVM 3.8

- oclint-metrics/include/oclint/metric/NPathComplexityMetric.h
- oclint-metrics/lib/NPathComplexityMetric.cpp
- oclint-metrics/test/NPathComplexityMetricTest.cpp
The nPath method for SwitchStmt casts the body to CompoundStmt. A switch
statement can also contain just a single case like this:
switch(arg)
case3: return 2;
Here the body is actually just a single SwitchStmt. We have to check the
actual type of the body before casting it to CompoundStmt and
potentially triggering UB.
This should address #323, but needs a test that covers the new branch.
> Fix segfault in NPathComplexityMetric

- oclint-driver/include/oclint/CompilerInstance.h
- oclint-driver/lib/CompilerInstance.cpp
The FrontendAction stored in the _actions vector was never deleted.
The unique_ptr now takes care of this.
> Fix memory leak in CompilerInstance

- oclint-scripts/test
The 'call' helper function in oclintscripts call sys.exit if the
subprocess exits with a non-zero exit code. This prevented the test
script from printing out the ctest output after a failed test.
> Show test failures

- oclint-scripts/scaffoldRule
The original scaffoldRule script can not generate correct cmakefile of test.
> Fix scaffoldRule

- oclint-driver/main.cpp
LLVM's code for printing the version uses it's `outs()` stream instead
of `cout`. OCLint was using `cout` which doesn't always flush correctly
before the program exits. In particular, when using bash pipes or
redirects.
Tested it by running `../build/oclint-driver/bin/oclint-0.10.4
--version`
> use LLVM outs for printing OCLint version

- oclint-driver/lib/CompilerInstance.cpp
If FrontendAction::BeginSourceFile fails calling Execute causes
undefined behaviour. This can happen for example if the file does not
exist.
In such a case we should skip this file and move on to the next.
Fixes #353
> Fix segfault if file does not exist

- oclint-reporters/reporters/PMDReporter.cpp
- oclint-reporters/test/PMDReporterTest.cpp
The pmd report did not contain the static analyzer bugs when
`-enable-clang-static-analyzer` was set.
As the Violations generated by the dispatcher do not have a rule we just
set the priority to 2 and the rule and ruleset to "clang static analyzer".
> Add clang static analyzer bugs to pmd report

- oclint-driver/lib/ConfigFile.cpp
- oclint-scripts/oclintscripts/path.py
- oclint-scripts/oclintscripts/version.py
Even though the official LLVM/Clang prebuilt binaries have not been published, the `final` branch has been tagged already right before Apple's Sept 7 media event. So I am catching up with its changes, and hopefully it can unblock some Xcode 8 beta users.
> Catching up with LLVM 3.9.0 final branch

- oclint-rules/rules/convention/MissingBreakInSwitchStatementRule.cpp
- oclint-rules/test/convention/MissingBreakInSwitchStatementRuleTest.cpp
Like break, return, etc., continue can escape the flow of a switch
statement when used inside a loop. It should not trigger the
MissingBreakInSwitchStatementRule.
Fixes #355
> Treat continue as a break in switch statement

- oclint-scripts/oclintscripts/version.py
This pull request tries to fix the broken build script when oclint is downloaded from source code as compressed archives instead of as a git clone.
> Return `src` for dev build from source code

- oclint-reporters/reporters/PMDReporter.cpp
- oclint-reporters/test/PMDReporterTest.cpp
The message from the clang static analyzer may contain < and > symbols
which are common in templated code. These would be interpreted as
opening tags by the parser.
Fixes #384 
Maybe we should think about using a library for handling the xml/html/pmd reports.
> Escape clang static analyzer message in pmd report

- oclint-driver/lib/Analytics.cpp
- The `oclint::Analytics::langOption()` method doesn't handle ObjC2 correctly. 
- This PR adds support for checking either ObjC language version.
> Handle ObjC2 langOpts

- oclint-reporters/reporters/PMDReporter.cpp
- oclint-reporters/test/PMDReporterTest.cpp
This is a minor refactoring that is needed to implement reporting compilation errors and warnings in PMD reporter (https://github.com/oclint/oclint/issues/398).
> Duplication in PMD reporter is eliminated; additions to PMD reporter tests

- oclint-rules/rules/convention/MissingBreakInSwitchStatementRule.cpp
- oclint-rules/test/convention/MissingBreakInSwitchStatementRuleTest.cpp
The MissingBreakStatement rule does not handle throw accordingly, if there are multiple commands, before exiting with throw/return with a new created object.
Example of incorrect behaviour can be seen in case 3 and 4 of the appended test.
I am quite sure, that more deeply chained, but correct switch break statements, are still handled incorrectly, such as throw/return within loops and try/catch clauses. But I have not tested such code yet.
> Correct false/postive in MissingBreakStatement

- oclint-rules/rules/size/LongMethodRule.cpp
- oclint-rules/test/size/LongMethodRuleTest.cpp
It is legal in c++ to leave out the curly braces of function and just
have a single statement like a try-catch or a while loop as the function
body. If we encounter such a method in applyDecl, the dyn_cast will fail
because it is not a CompoundStmt and we get a segfault on a nullptr.
Thankfully, the parent class Stmt also has the getSourceRange() method
that works just as expected from what I have tested so far.
Fixes #467
> Fix segfault on methods without CompoundStmt

- oclint-reporters/reporters/PMDReporter.cpp
- oclint-reporters/test/PMDReporterTest.cpp
Currently PMD reporter doesn't escape ', " and & in compiler warning and clang static analyzer message. SonarQube plugin fails on parsing PMD XML report file.
Part of PMD XML report file before fix:
```
<file name="somefile.m">
<violation begincolumn="13" endcolumn="0" beginline="10" endline="0" priority="2" rule="compiler warning" ruleset="clang" >
variable 'a' is used uninitialized whenever '&&' condition is false
</violation>
</file>
```
After fix applied to oclint:
```
<file name="somefile.m">
<violation begincolumn="13" endcolumn="0" beginline="10" endline="0" priority="2" rule="compiler warning" ruleset="clang" >
variable &apos;a&apos; is used uninitialized whenever &apos;&amp;&amp;&apos; condition is false
</violation>
</file>
```
> Escape ', " and & in violation message in PMD XML report file

- oclint-reporters/reporters/XMLReporter.cpp
The string in sprintf is exactly 21 characters long. 20 for the string
itself and then an additional null byte. This did not fit in the given
array.
Fixes #473
> Fix out of bounds write in XMLReporter

- oclint-scripts/bundle
If the llvm-root option is passed to bundle, the script attempts to
copy the cpp headers from an incorrect location (namely, where oclint
would build them itself).
This commit corrects the path to the cpp headers if the llvm-root
option is passed to bundle so that bundle copies the required headers
from the correct location within the existing LLVM install prefixed by
args.llvm_root.
> bundle: fix cpp header install dir

- oclint-driver/lib/ConfigFile.cpp
- oclint-reporters/reporters/XMLReporter.cpp
- oclint-scripts/build
- oclint-scripts/bundle
- oclint-scripts/ci
- oclint-scripts/clang
- oclint-scripts/dogFooding
- oclint-scripts/googleTest
- oclint-scripts/oclintscripts/cmake.py
- oclint-scripts/oclintscripts/environment.py
- oclint-scripts/oclintscripts/path.py
- oclint-scripts/oclintscripts/process.py
- oclint-scripts/oclintscripts/version.py
- oclint-scripts/scaffoldReporter
- oclint-scripts/scaffoldRule
- oclint-scripts/test
- oclint-scripts/upload
Since Python 2 has reached its end-of-life, and Linux distros such as Ubuntu 20.04 no longer ship with Python 2, upgrading to Python 3 seems like the right move.
This branch also fixes a couple of compiler warnings from GCC 9.3.0.
> Update build scripts to Python 3

- oclint-scripts/build
- oclint-scripts/ci
- oclint-scripts/oclintscripts/environment.py
- oclint-scripts/oclintscripts/version.py
Remove unused imports
Calling python using `sys.executable` instead of just python/python3
> Small improvements in Python scripts
